version: '3.4'

services:
  shopping.api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile

  shoping.client:
    image: ${DOCKER_REGISTRY-}shopingclient
    build:
      context: .
      dockerfile: Shoping.Client/Dockerfile

  shopping.db:
    image: mongo


